excluded:
  - ConsciousTests
  - ConsciousUITests

opt_in_rules:
  - empty_count

disabled_rules:
  - function_body_length

type_body_length:
  - 250 # warning
  - 400 # error

file_length:
  - 500 # warning
  - 1000 # error

custom_rules:
  unneeded_filter:
    name: "Possible Unneeded Filter"
    regex: ".filter(\\s?)\\{(.+)\\}\\s+for (\\w+) in (\\w+) \\{\\s*(.+)\\s*\\}"
    message: "Filter might be unneeded; try using the for-where clause to iterate over a filter."
    severity: warning
